version: '2'
services:
  boinc-client:
    build: ./boinc-client
    restart: always
    ports:
      - 31416:31416
  ui:
    build: ./ui
    restart: always
    privileged: true
    ports:
      - 80:80
      - 8080:8080
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
  power-management:
    build: ./power-management
    restart: on-failure
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
