version: '2'
services:
  boinc-client:
    build: ./boinc-client
    restart: always
    ports:
      - 31416:31416
  web-ui:
    build: ./web-ui
    restart: always
    ports:
      - 80:80
  power-management:
    build: ./power-management
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
